### ISSUE TITLE
Acceptance test for create organizers no logged users

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#117]
Following the need to have main acceptance tests as #97 , we need to cover a basic flow to create a new organizer

### Screenshot attached

![pageshot of truppie 2018-04-03-2103 03](https://user-images.githubusercontent.com/88840/38329039-d8d8bdc2-384c-11e8-90e2-0c6421eff2fa.png)

So we need to create the follow requirements to be created as a new feature like this

```

Feature: Create a new organizer
  As an non registered user
  I want to setup a organizer account
  So I be able to offer tours and guidebooks

  @javascript
  Scenario: Non logged user create a organizer
    Given I go to the homepage
    And I click in register guide
    And I fill the guide information
    And I click in finish 
    And I create an user account
    Then I see the guide profile page

```

### Screenshot attached

![pageshot of truppie 2018-04-03-2032 24](https://user-images.githubusercontent.com/88840/38326998-732d3dea-3847-11e8-828a-f6aee56cf00b.png)

### How to reproduze the user scenario

 - Go to homepage
 - Click in [register guide](https://truppie.com/welcome/organizer?locale=en)
 - Fill up the form with the required information
 - We should have a new account and go to profile page

More details in how to contribute, [read the contribution guidelines](https://github.com/worknenjoy/truppie/blob/master/CONTRIBUTING.md)

**Comment by alexanmtz** [comment]
pronto @amandaclarck , agora temos uma tarefa para ela e atualizei algumas informações de como seriam os cenários de teste, mas fique a vontade de propor uma solução caso seja diferente desta, pois é apenas uma idéia. Qualquer coisa é só falar!

**Comment by alexanmtz** [comment]
@amandaclarck devido aos problemas com a sessão do rails para armazenar dados do formulário e os passos extras, eu refiz esta parte para integrar a criação do usuário e guia em um passo #119 

Agora fica mais fácil testar, basta preencher os dados do formulário corretamente para criar um perfil de guia e um usuário

**Comment by amandaclarck** [comment]
@alexanmtz Sei que a pergunta pode parecer um pouco boba, mas então esses testes serão os que substituirão os que já foram feitos, certo? Ou será adicionado aos testes que já foram feitos?

**Comment by alexanmtz** [comment]
@amandaclarck a pergunta boba é aquela que não é feita 😃 

Os testes não terão que ser substituídos (ufa!), pois para o usuário que já está logado e quer criar uma conta como guia permanece o mesmo fluxo que você cobriu com testes. Inclusive estes testes ajudaram a manter esta parte funcionando como antes, garantido que este caso não quebre depois de eu ter feito uma modificação desta.

Agora precisa adicionar o teste que cobre o caso dele não logado, e ai tem que considerar estas mudanças, que no final ficou mais simples tanto no sistema quanto para testar.

Antes eu mantia o mesmo form (usuário logado ou não) e na hora de concluir a criação de um guia (model `organizer`) como não tinha um usuário logado ele iria para a tela de login, criava uma conta e era redirecionado. 

O problema é que os dados enviados eram perdidos neste tempo, sendo que passei a usar a sessão para armazenar. O problema foi que a sessão não suporta tantos dados, pois o cadastro tem imagens, e ai virou um problema muito grande. Em termos de fluxo, também estava bem confuso, e os clientes não estavam entendendo o que eles estavam criando.

Agora tenho um form transparente, que quando o usuário que quer ser guia não está logado com uma conta na Truppie, ele já cria ali o email de usuário como guia com usuário e senha e ai na criação do model `organizer` criamos um usuário primeiro (obrigado ao Devise de permitir) e já loga no sistema e atribui este usuário ao guia. O fluxo de teste que propus aqui deve cobrir isto, dado que o usuário não está logado, preenchendo este formulário ele vai para o perfil do guia assim como no outro teste. A diferença aqui é que ele vai preencher os campos senha para já criar uma conta.

Espero que tenha ficado claro e qualquer dúvida me avise. Me diga também se vai seguir com isto para finalizarmos esta issue e ter esta parte completa.

E esta semana teremos mais tarefas 💻

**Comment by amandaclarck** [comment]
@alexanmtz obrigada por responder! Como sempre, só consigo pegar fds o freela mas vou querer sim! Se eu tiver mais dúvidas eu volto a falar aqui

**Comment by alexanmtz** [comment]
@amandaclarck tem alguma previsão de quando poderá enviar o PR?

**Comment by alexanmtz** [comment]
Merged in #131 

Thanks for the contribution @amandaclarck
