### ISSUE TITLE
Orders from Guidebooks

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#130]
List orders of the model `Guidebooks`, like it is listed on the screenshot for `Tour`

To see an order, you will need to mock one, assuming that you create a `User` and a `Guidebook`.

### Screenshot attached

![pageshot of truppie 2018-07-02-1746 36](https://user-images.githubusercontent.com/88840/43470879-ef2566f8-94e9-11e8-9a9c-bb052722c6e2.png)

More details in how to contribute, [read the contribution guidelines](https://github.com/worknenjoy/truppie/blob/master/CONTRIBUTING.md)

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/60

**Comment by cleicar** [comment]
Hi @alexanmtz, I am interested in this task!

**Comment by alexanmtz** [comment]
Hello @cleicar, good to see you again 😄 

I assigned you and you're ready to start. Let me know an estimation when you think will be possible to finish.

I will kindly ask you as well to show your interest here https://gitpay.me/#/task/60 to receive the payment after you send the PR. 

And feel free to comment here if you have any doubt about this issue.

**Comment by cleicar** [comment]
Hi @alexanmtz! Is good to be back :)

Can you add the steps to reproduce the scenario? I didn't fully understand.

Thanks!

**Comment by cleicar** [comment]
Hi @alexanmtz did you check my last comment?

**Comment by alexanmtz** [comment]
Hey @cleicar , sorry to not have so much details on this. Here the steps to reproduce:

1. Create a user account
2. Create a business account (`Organizer`) (in "Cadastrar negócio")
3. Create, as business account (`Organizer`) a new Tour and a new Guidebook (Tour guiados e Roteiros)
4. Make a reservation for each one as an user account (The card number for test is 4242424242424242), and you need to fill all personal information and a valid end date)
5. If you click in "Minhas truppies" that is on top right corner when you create in your logged user, you will see the screenshot, and just with one order from a tour

We need to show both, so you can create a template to display a table for each category (Tours guiados e Roteiros, that is related with the models `Tour` e `Guidebook`).

Another way is create a user account, go to the rails console and create an order directly in the model, one associated with `Tour` and other associated with `Guidebook`, this order should display in the orders page.

Let me know if you need any other information.

Thanks!

**Comment by alexanmtz** [comment]
Merged and deployed 🚀 , thanks for the contribution @cleicar
