### ISSUE TITLE
Documentar o processo de boas práticas de integração de código

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#35]
Criar uma página de documentação mostrando como realizar merge usando o rebase como padrão.

Desta forma, facilita a integração dos pull-requests sem necessidade de linha de comando, e sendo possível ser feita pela própria interface do Github.

Sempre realizar rebase na hora de integrar o código e fazer pull request, e mostrar também o processo de `squash` de forma básica, de forma a esclarecer as melhores práticas para realizar o pull request.

Não é necessária experiência para esta tarefa, ela pode ser um modo de aprender e ajudar outros da comunidade não só para colaborar com este projeto mas com projetos Open Source que em geral seguem estas práticas. Sendo assim, você pode pesquisar a respeito e documentar aqui para ser avaliado por mim e por todos e assim aprender fazendo.

### Como chegar no cenário descrito

 - Você deve estar ciente das práticas de rebase e como configurar o rebase como padrão para merges.
 - Você deve pesquisar sobre Github pages para saber que esta página irá fazer parte da documentação do projeto e saber como criar novos arquivos de documentações.
 - Esta página deve ser criada dentro da branch `gh-pages`

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentação](https://trello.com/c/v47A10UO/544-documenta%C3%A7%C3%A3o)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Guia no Truppie devs para rebase](https://trello.com/c/oIz2ksfu/534-guia-no-truppie-devs-para-rebase)

**Comment by amandaclarck** [comment]
Tenho interesse :)

**Comment by alexanmtz** [comment]
Opa amanda, muito bom, assim que terminar a outra e se ninguém tiver pegado seguimos adiante 🔢

**Comment by viniciusfmaciel** [comment]
Também tenho interesse em executar essa tarefa @alexanmtz

**Comment by alexanmtz** [comment]
@viniciusfmaciel Pode começar!

Você pode criar um arquivo CONTRIBUTING.md na branch `gh-pages` que criaremos uma seção para ela no http://dev.truppie.com! chamada _Como contribuir_

Você quer aprender sobre o Jekyll e como hospedar uma página no Github Pages? Depois da documentação realizada poderemos integrar na página e posso lhe orientar passo a passo 🔢

**Comment by viniciusfmaciel** [comment]
@alexanmtz Legal vou começar então.
Quero aprender sim sobre o Jekyll.

Vamos conversando para alinhar as coisas.

Valeu, um abraço.
