### ISSUE TITLE
Opção de envio de notificações ao guia opcional

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#46]
Criar um novo campo no modelo `organizer` que irá condicionar o envio de email de boas vindas quando um novo guia se cadastrar no sistema.

Isto será feito pois muitas vezes a criação do guia poderá ser feita através de convite e neste caso não é necessário mandar boas vindas, bem como cadastros de guias feitos por nós.

### Como chegar no cenário descrito

 - Entrar na página principal
 - Ir em Área do guia
 - Criar um novo guia
 - Você receberá um e-mail de boas vindas

 - Entrar como adminstrador (instruções abaixo)
 - Ir em `/organizers`
 - Ir em _new organizer_
 - Checkbox com opção de notificar guia

### Parte 2: Adicionar ao form geral do organizer um checkbox _notificar por e-mail?_

Critério de aceitação:

- [ ] Quando um guia criar uma conta dentro da plataforma, receber um e-mail de boas vindas
- [ ] Quando um administrador criar uma conta de guia para enviar um convite posteriormente ele ter uma opção "notificar por e-mail" que quando marcado envia um convite, caso contrário não envia o e-mail de boas vindas na criação de um novo `organizer`

### Considerações sobre a plataforma:

- Criar as migrations relacionadas

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, seu código é integrado

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [email de boas vindas ao guia opcional](https://trello.com/c/MFtfsDPS/568-email-de-boas-vindas-ao-guia-opcional)

**Comment by amandaclarck** [comment]
Quero essa, @alexanmtz :)

**Comment by amandaclarck** [comment]
@alexanmtz Tudo bem?  Estou tentando me cadastrar como guia seguindo o fluxo Área do Guia > preencher dados > preencher localização > continuar e no último passo (concluir)  o console me mostra que não estou autorizada. Pode me ajudar com isso? Iniciei essa tarefa hoje e estou no fluxo de testar se recebo o e-mail como uma nova guia.

![image](https://user-images.githubusercontent.com/11525900/33531789-4526a8ec-d879-11e7-8c08-55b934b0ab85.png)

**Comment by amandaclarck** [comment]
@alexanmtz Vale lembrar que eu segui o fluxo indicado aqui de PR: criei a branch a partir da master atualizada e dei rebase

**Comment by alexanmtz** [comment]
olá @amandaclarck, obrigado por relatar este caso. Eu reproduzi aqui e realmente temos um bug. Acabei de subir para o `master` uma correção temporária.

@hugohernani eu tive que tirar o `ajaxSync` que você colocou por que ele não direciona para a página de login, apenas dá um retorno do ajax de não autorizado. Tem como dar uma olhada nisto, se tem alguma mudança simples para este caso. Não tinha pegado estes casos nos testes e isto compromete cadastro de novos clientes.

Não se esqueça também @amandaclarck que para ser admin e poder ter acesso de edição de algumas informações para esta tarefa, você precisa criar na raíz do projeto um arquivo `.env` com o seguinte conteúdo:

```
ADMIN_EMAIL=seuemail 
ADMIN_EMAIL_ALT=outro email de admin se quiser
```

E então se cadastrando com o mesmo email do `.env` você se torna admin

Então agora acho que dá para seguir em frente.

Qualquer dúvida é só falar.

**Comment by amandaclarck** [comment]
@alexanmtz Olá, tudo bem?

Eu consigo simular o envio de email em ambiente localhost? Se não, como eu poderia fazer para que eu pudesse simular o fluxo do guia se cadastrar na plataforma > enviar email de boas vindas?

Obrigada

**Comment by amandaclarck** [comment]
Ah, esquece @alexanmtz. Acredito que com os testes automatizados eu consiga simular o que eu quero com o envio de emails :)

**Comment by alexanmtz** [comment]
Isso @amandaclarck , já tem testes com um fluxo parecido e você consegue simular sem ter que fazer nenhum fluxo na interface, aí os testes automatizados reinam. Existe uma asserção que você verifica se seguindo um fluxo o e-mail foi enviado.

Você pode ver se foi enviado criando uma nova coluna no banco `organizer` e se tiver este atributo no teste verificar se ao chamar o controller de criar um novo `organizer` com esse atributo ativado ele envia o e-mail caso contrário não enviar. O único teste que você irá precisar fazer na interface é certificar-se que este campo está no formulário de criação de um `organizer` e ativando no checkbox este novo `organizer` terá este atributo (você pode verificar no console mesmo).

De qualquer forma, se você quiser fazer um fluxo completo para testar no final de forma local os e-mails acredito que serão enviados.

Qualquer dúvida que precisar só falar!

**Comment by alexanmtz** [comment]
@amandaclarck como tá indo? Eu estou com alguns clientes interessados para fazer uma demonstração e esta funcionalidade será a base para isto.

**Comment by amandaclarck** [comment]
@alexanmtz olá, tudo bem? eu estou mexendo ainda. quero ver se consigo entregar nesse fds

**Comment by alexanmtz** [comment]
Seria ótimo @amandaclarck , pois tem um evento para o carnaval que precisamos começar a divulgar e para demonstrar o guia eu preciso desta funcionalidade. É uma ótima oportunidade para buscarmos novos clientes!

**Comment by amandaclarck** [comment]
@alexanmtz perfeito. Ontem mexi mais um pouco e vou fazer o máximo pra entregar nesse final de semana.

**Comment by amandaclarck** [comment]
@alexanmtz Será que posso pedir ajuda com os testes? Eu li o que você falou  (fluxo de teste) porém eu tenho mais experiência com Rspec, acaba que estou um pouquinho perdida nessa questão.

  ```  test "send welcome email to organizer" do
    o = organizers(:mkt)

    mail = OrganizerMailer.notify(o, "activate").deliver_now
    assert_not ActionMailer::Base.deliveries.empty?
    assert_equal ["ola@truppie.com"], mail.from
    assert_equal ["mail@foo.com"], mail.to
    case o.mail_notification
    when true
        assert_equal "Olá #{o.name}, sua conta na Truppie foi criada!", mail.subject
    end
  end```
Assim seria um teste válido? Eu já deixei por padrão como true a mail_notification no objeto de teste, não sei se é a melhor ideia. Me parece um pouco 'seco' demais (sim, sei que tem o caso de falha que devo testar, mas é só o começo hehe). Estou me baseando no [test guide](http://guides.rubyonrails.org/testing.html) do Rails.

Outra dúvida é se é válido esse teste, pois é muito parecido com o new. A questão é que estou testando para o método create, então pode ser que eu esteja fazendo errado o fluxo.
![image](https://user-images.githubusercontent.com/11525900/35771524-42057b4e-0915-11e8-9a84-3ba5bdf78b8a.png)

Já o teste para interface eu não entendi como fazer, rs. O único que usei para isso foi o Cucumber.

**Comment by alexanmtz** [comment]
@amandaclarck , o teste de interface não precisa, você pode testar realmente fazendo o fluxo quando você validar os models. Eu não uso o Rspec apesar de gostar bastante também, este é o MiniTest e é mais simples, comecei o projeto com ele e agora para reescrever todos os testes seria mais complicado.

O seu fluxo está correto e o request tem que ser feito pro `create`, mesmo com testes parecidos com o new. Este teste será focado em verificar os dois casos de envio de e-mail, um com a opção de enviar a notificação como `true` no model e outro como `false`, você pelo que parece fez um caso, mas só faltou aí mesmo o request que é fazer um post como em outros testes pro `organizer/create` e não usar a função mail, pois ela é chamada dentro do controller.

Neste caso você não tem que testar o envio de e-mail, usando a função de envio (`deliver_now`), isto seria um teste do mailer para ver se o e-mail está correto (possui o template, espera algum conteúdo etc, e isto já está testado). O que você precisa validar é que ao enviar os dados de um organizer para o `create` ele vai criar com sucesso e enviar o e-mail caso esteja ativado para receber boas vindas.

O teste será parecido com isso aqui com o fato da linha comentada ser de fato usada:
[https://github.com/worknenjoy/truppie/blob/master/test/controllers/organizers_controller_test.rb#L57](https://github.com/worknenjoy/truppie/blob/master/test/controllers/organizers_controller_test.rb#L57)

Então ficaria assim

```
test "should send notification to organizer for default" do
     assert_difference('Organizer.count') do
       post :create, organizer: @organizer
     end
     assert_not ActionMailer::Base.deliveries.empty?
     assert_equal flash[:notice], "Sua conta como guia foi criada com sucesso"
     assert_redirected_to organizer_path(assigns(:organizer))
   end
```

O `assert_not ActionMailer::Base.deliveries.empty?` será verdade se o @organizer tiver o envio ativado, se for ativado por padrão este teste deve passar 

O outro caso seria pegar o `@organizer`, atualizar o atributo de enviar notificações para false (utilizando `update_attributes` e teste verificar se `assert ActionMailer::Base.deliveries.empty?`

Na interface, você colocaria um checkbox no cadastro para ativar ou não a notificação e com estes testes na parte dos controllers realizados você consegue fazer o fluxo na interface só verificando que ao criar um organizer pelo form de admin ([https://github.com/worknenjoy/truppie/blob/master/app/views/organizers/_form.html.erb](https://github.com/worknenjoy/truppie/blob/master/app/views/organizers/_form.html.erb)) ele vai passar os dados corretamente, já que recebendo os dados no teste você garantiu os dois casos.

Acho que é isso qualquer dúvida é só falar!

**Comment by amandaclarck** [comment]
@alexanmtz tudo bem?

Estou fazendo o teste segundo seu modelo:
```    test "should send notification to organizer for default" do
     assert_difference('Organizer.count') do
       post :create, organizer: @organizer
     end
     assert ActionMailer::Base.deliveries.empty?
     assert_equal flash[:notice], "Sua conta como guia foi criada com sucesso"
     assert_redirected_to organizer_path(assigns(:organizer))

     @organizer = Organizer.last
     @organizer.update_attributes(:mail_notification => false)
     assert_not ActionMailer::Base.deliveries.empty?
    end```

Porém o último action mailer está como true e por isso não consigo usar o assert_not, mas queria que ele fosse falso

**Comment by alexanmtz** [comment]
@amandaclarck se ele está como true é por que o e-mail está sendo enviado

No caso isto acontece por que você está atualizando o atributo após o `post :create, organizer: @organizer`

Ele tem que ser atualizado antes, pois é exatamente neste post no `create` que faz a requisição e cria o e-mail, então este update tem que ser feito no início do testes, antes de qualquer coisa.

Qualquer outra dúvida é só falar!

**Comment by alexanmtz** [comment]
pull request #69 integrado
