### ISSUE TITLE
Opção Esqueceu sua senha - Apresenta mensagem fora do padrão.

### ISSUE THREAD

**Issue by mthais** [worknenjoy/truppie#54]
Quando o usuário que não esta cadastrado no sistema, tenta recuperar sua senha o sistema apresenta mensagem fora do padrão.

### Como chegar no cenário descrito

 - Entrar na página principal
 - Clicar no botão "Entrar"
 - Clicar no link "Esqueceu sua senha"
 - Inserir email não cadastrado no sistema
 - Sistema apresenta mensagem no cabeçalho fora do formato.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato .
2. [Faça um fork do projeto]
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo ambiente para testes será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍

**Comment by cleicar** [comment]
@alexanmtz essa task está disponível?

**Comment by alexanmtz** [comment]
sim @cleicar !

**Comment by alexanmtz** [comment]
@cleicar você já começou? Pode atribuir esta tarefa a você oficialmente?

**Comment by cleicar** [comment]
@alexanmtz sim, vou enviar um PR em breve.

**Comment by alexanmtz** [comment]
Fiz um comentário @cleicar , parece estar tudo certo com o código, só tem umas questões do git mesmo a ser melhorada para podermos testar! Qualquer dúvida é só falar.

**Comment by cleicar** [comment]
@alexanmtz eu usei o rebase para corrigir o branch e enviei um novo PR. Por favor, me avise se estiver com algum erro/problema.

**Comment by alexanmtz** [comment]
olá @cleicar , se observar lá ainda está vindo vários commits. Ele deveria vir com um somente, que é o * Fix reset password error message to pattern * 

Acho que o que faltou foi dar um push com o parâmetro `-f` para forçar e reescrever o histórico corretamente.

Qualquer dúvida me fala e se não consegui posso pegar o seu commit e aplicar, mas seria legal se você visse na prática como tratar esse caso. Você pode criar uma branch do master do upstream e aplicar somente esta mudança que deve funcionar, ou forçar esta sempre que dar push com um `-f` para que ela force com sua versão acertada localmente

**Comment by cleicar** [comment]
@alexanmtz que estranho, quando eu estava criando o PR apareceram apenas meus dois commits, não sei o que aconteceu. 

Enfim, fiz como você sugeriu criei um novo branch apartir do upstream/master e acredito que deu certo.
Submeti um novo PR agora :)
