### ISSUE TITLE
Atualizar o Rails para 4.2.7.1

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#61]
Atualizar o Rails para a versão `4.2.7.1` e verificar que foi concluída com sucesso

Se isto gerar algum bug apresentar para que possamos atualizar o que for preciso, pois como mostrado na tela abaixo, estamos recebendo avisos de vulnerabilidade no site. Então esta tarefa é uma tarefa importante para infraestrutura.

![screen shot 2018-02-02 at 12 11 36 pm](https://user-images.githubusercontent.com/88840/35751896-57389214-085a-11e8-90bd-de53e4ae017c.png)

### Como chegar no cenário descrito

 - Atualizar o rails no `Gemfile`
 - Verificar que o site continua funcionando

Critério de aceitação:

- [ ] Os testes precisam passar após a atualização
- [ ] O site precisa executar normalmente

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, sua contribuição é realizada e você passa a fazer parte do projeto e contribuindo para uma empresa que utiliza o Open Source.

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍

**Comment by jcserracampos** [comment]
Eu posso ajudar nesta.

**Comment by alexanmtz** [comment]
Enviei um convite @jcserracampos, após você aceitá-lo lhe adiciono como membro e atribuo a você esta tarefa e ai pode começar!

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Atualizar Rails](https://trello.com/c/hFahuOIs/611-atualizar-rails)

**Comment by jcserracampos** [comment]
@alexanmtz Estou esperando acesso ao Trello.

**Comment by alexanmtz** [comment]
@jcserracampos já lhe atribui a tarefa e todos os detalhes dela estão aqui e o Trello é somente para priorização e concepção da tarefa.

**Comment by alexanmtz** [comment]
A organização do projeto fica toda aqui: https://github.com/worknenjoy/truppie/projects/1

**Comment by jcserracampos** [comment]
Já estou testando a atualização.

**Comment by alexanmtz** [comment]
Conseguiu testar @jcserracampos ?

**Comment by alexanmtz** [comment]
@jcserracampos , esta tarefa ficou parada muito tempo e vai voltar para o backlog, se tiver algo em alguma branch você pode passar ou até mesmo criar um pull request para a gente testar em uma nova app

**Comment by lucianojfj** [comment]
@alexanmtz Passa pra mim por favor.
