### ISSUE TITLE
Sinalizar campos obrigatórios na página de criação do guia

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#62]
### Como chegar no cenário descrito

 - Na parte do menu de *Oferecer serviço* e no cadastro de um novo guia temos a primeira etapa com todos itens obrigatórios. É preciso sinalizar.

### Parte 2: outro passo para realizá-la

Critério de aceitação:

- [ ] Quando um usuário entrar na página de registro do guia (guia.truppie.com) assinalar com `*` os campos obrigatórios e escrever _* campos obrigatórios_ 

### Considerações sobre a plataforma:

- Para esta tarefa consideramos somente o front-end, pois as validações já estão aplicadas. Você pode olhar o código para aprender a validar um model no Rails ou pode sugerir melhorias também, e se for capaz de fazê-los e quiser contribuir, seria de grande valia.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, você se torna colaborador do projeto e pode contribuir e ficar sabendo sempre da evolução do projeto e pode usá-lo como experiência, currículo e realizar tarefas oferecidas por clientes, e até mesmo pela Truppie. 

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by lucianojfj** [comment]
Posso ficar com esta?

**Comment by alexanmtz** [comment]
enviei um convite @lucianojfj , assim que você aceitar lhe atribuo a tarefa e pode começar ;-)

**Comment by lucianojfj** [comment]
@alexanmtz Aceitei. Esse link do Trello que você postou, tem alguma informação adicional?

**Comment by alexanmtz** [comment]
@lucianojfj é apenas para controle das tarefas e prioridades antes delas entrarem aqui:

https://github.com/worknenjoy/truppie/projects/1

**Comment by alexanmtz** [comment]
Você está nessa ainda @lucianojfj ? Ou posso passar para alguém?

**Comment by lucianojfj** [comment]
@alexanmtz Estou nela.

**Comment by lucianojfj** [comment]
Levando em conta as validações definidas no model _organizer_:
https://github.com/worknenjoy/truppie/blob/37499cb797c01fafae02cf29a3bd6845b9c231e9/app/models/organizer.rb#L35

Atualmente esses campos já estão sendo sinalizados, conforme imagem abaixo:
![screenshot from 2018-03-04 16-00-34](https://user-images.githubusercontent.com/3276943/36949365-ef936642-1fc5-11e8-8603-b081ed493f45.png)

**Comment by alexanmtz** [comment]
@lucianojfj sim já está definido, o que esta tarefa contempla é na exibição do formulário colocar um asterisco indicando que estes campos são obrigatórios para já ficar claro antes.

No caso exibir um asterisco nos campos desta primeira etapa e uma indicação:

`* campos obrigatórios`
