### ISSUE TITLE
Redirecionar guia logado para o perfil

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#63]
Quando for para a área do guia e ele estiver logado e com uma conta de guia, ir direto para o perfil

### Como chegar no cenário descrito

 - Criar uma conta de guia
 - Após logado e com essa conta, você entra de novo na seção "Oferecer serviço"
 - Ele vai para a página de ativação de conta, onde pode cadastrar `tours`
 - O cadastro aparece novamente, ao invés disso, enviá-lo para a página da sua conta que é a mesma da falada no item anterior

### Considerações sobre a plataforma:

- Esta é uma mudança nos `routers` do rails, onde você pode direcionar o usuário de acordo com o seu login ou criação de uma conta.

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, o **pagamento é enviado**

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quando for para a área do guia e ele estiver logado e com uma conta, ir direto para o perfil](https://trello.com/c/sOi2RY4Z/564-quando-for-para-a-%C3%A1rea-do-guia-e-ele-estiver-logado-e-com-uma-conta-ir-direto-para-o-perfil)

**Comment by cleicar** [comment]
@alexanmtz Posso ficar com essa?

**Comment by danilocandido** [comment]
Ainda tá livre essa atividade? Tenho interesse.

**Comment by alexanmtz** [comment]
@danilocandido enviei um convite para você, @cleicar preciso de você para outra

**Comment by cleicar** [comment]
@alexanmtz claro. Qual?

**Comment by alexanmtz** [comment]
Verás :1st_place_medal:

**Comment by danilocandido** [comment]
@alexanmtz, recebi o convite. :+1:

**Comment by danilocandido** [comment]
Pessoal.
Sobre esse requisito abaixo tenho duas dúvidas: 

- "para isto, basta criar um arquivo .env com os campos"

1º - Esse arquivo .env deve ter que nomenclatura? Ex: nome_do_arquivo.env
2º - Em que diretório devo salvar esse arquivo?

**Comment by alexanmtz** [comment]
@danilocandido , não se preocupe, o acesso ao trello é apenas para quem for testar acompanhar o status no github.

Respondendo suas perguntas:

1. Esse arquivo .env deve ter que nomenclatura? Ex: nome_do_arquivo.env
Ele tem que se chamar `.env`, exatamente assim, é uma prática para guardarmos variáveis de ambiente localmente

2. Deve ser salvo na raiz do projeto

Este .env deve conter o seu e-mail para que você fique como adminstrador localmente, e que você crie uma conta na plataforma localmente com este mesmo e-mail.

Qualquer outra dúvida, só falar!

**Comment by danilocandido** [comment]
Pessoal tô com uma dúvida.
Fiz o caminho do sucesso:  Quando o usuário for admin com conta de guia, **enviá-lo para a página da sua conta**

Porém quando for um usuário que não for Admin, para onde devo direciona-lo?
Qual o comportamento? Pois o botão "Oferecer serviço" aparece para quem não é admin também?

**Comment by danilocandido** [comment]
Mandei o Pull Request #70

**Comment by alexanmtz** [comment]
@danilocandido seu pull request foi aceito e integrado, logo ele irá para o site para testes

**Comment by alexanmtz** [comment]
@danilocandido depois de integrado o seu código, tivemos um problema quando não há usuário logado e assim a página quebra pois não tem um current user, eu adicionei outro commit que verifica antes se existe um `current_user` antes de cair nas condições que você inseriu. Dá uma olhada depois, agora está completo e muito obrigado pela contribuição!
