### ISSUE TITLE
Mobile friendly - Aprenda Bootstrap para mobile na prática

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#64]
Algumas mudanças necessárias para o projeto precisam ser realizadas para a Truppie funcionar bem nos dispositivos móveis. Cerca de 40% dos acessos são por lá.

Usamos o sistema de grid do Bootstrap e pra isso algumas melhorias precisam ser feitas na visualização no mobile e esta é uma ótima maneira de aplicar seus conhecimentos de Bootstrap na prática.

Áreas que precisam ser melhoradas:

- [ ] Cadastro do guia
- [ ] No safari a logo aparece com o fundo preto

### Considerações sobre a plataforma:

- A plataforma usa o Bootstrap 4.0 alpha com grid para mobile. Existe um CSS também com as media-queries

### Requisitos para rodar a plataforma

- Ruby
- Postgres
- Se tornar administrador no sistema
(para isto, basta criar um arquivo .env com os campos:

```
 ADMIN_EMAIL=seuemail 
 ADMIN_EMAIL_ALT=outroemail
```

### Como realizar esta tarefa

1. Comente aqui manifestando o interesse em realizar esta tarefa, que entrarei em contato para obter os detalhes para realizar o pagamento
2. [Faça um fork do projeto](http://desenvolvimentoparaweb.com/miscelanea/como-fazer-fork-de-um-projeto-no-github/)
3. Faça um `clone` do projeto para o seu ambiente local

`rake test` (rodar os testes automatizados)

`rails db:migrate` (Rodar as `migrations` para o banco de dados)

`rails s` (Rodar o projeto)

4. Realize as modificações como descrito nesta Issue
5. [Enviar um Pull Request](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
6. Certificar-se de que as modificações [passaram nos testes automatizados](https://blog.da2k.com.br/2015/02/04/git-e-github-do-clone-ao-pull-request/)
7. Um novo **ambiente para testes** será criado para validação das modificações com a nossa equipe
8. Receber os comentários e feedbacks sobre modificações
9. Enviar quaisquer modificações necessárias até ser aprovado
10. Você ganha então um 👍 
10. Quando o _Pull Request_ for finalizado, você contribuiu para o projeto e faz parte dele para novas mudanças, e pode continuar contribuindo com o open source e receber ofertas de empresas para trabalhos sob demanda.

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 

Se quiser se familiarizar com o funcionamento de projetos de software livre, tem este [excelente guia do Tableless](https://tableless.com.br/contribuindo-em-projetos-open-source-com-o-github/)

### Como ter um pull request aceito e integrado da forma correta no projeto

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.

Se tiver dúvidas como fazer isto dá uma olhada aqui [neste post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

Se precisar de qualquer ajuda ou tiver qualquer dúvida basta comentar aqui que as dúvidas poderão ser respondidas por qualquer pessoa da comunidade ou quem contribui com o projeto e principalmente eu 👍 o

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mobile friendly](https://trello.com/c/kOKmMrzH/525-mobile-friendly)

**Comment by KaiqueMunhoz** [comment]
Não estou muito familiarizado com ruby on rails porém acredito que consigo realizar esses ajustes no Bootstrap. Se quiser passar para mim @alexanmtz, vou informando caso encontre dificuldades.

**Comment by alexanmtz** [comment]
Um convite foi enviado para você @KaiqueMunhoz e assim que aceitar posso lhe atribuir a esta tarefa, e fique a vontade para ajustar e se familiarizar com o Rails

**Comment by KaiqueMunhoz** [comment]
Perfeito. Aceitei o convite.

**Comment by alexanmtz** [comment]
Tá contigo @KaiqueMunhoz 🌟

**Comment by KaiqueMunhoz** [comment]
@alexanmtz Estou tendo problemas com a instalação da gem nokogiri. Atualmente tenho usado windows por causa de serviço e não estou com nenhuma maquina Linux para trabalhar com Rails. Assim que eu resolver esse problema de instalação trago um feedback.

**Comment by alexanmtz** [comment]
@KaiqueMunhoz Eu já tive algum problema relacionado ao nokogiri no Mac também. Sem problemas. Na verdade é bom saber que tem alguém rodando em uma outra plataforma. Quando resolver se tiver algo que possa ajudar fique a vontade para inserir informações da instalação no Windows.

**Comment by alexanmtz** [comment]
alguma novidade sobre esta issue @KaiqueMunhoz ?

**Comment by KaiqueMunhoz** [comment]
Sem sucesso em rodar o ambiente no windows @alexanmtz x

**Comment by alexanmtz** [comment]
@KaiqueMunhoz você pode tentar com o suporte a Docker feito pelo @lucianojfj

**Comment by KaiqueMunhoz** [comment]
Dessa vez quase foi @alexanmtz . @lucianojfj , rodei o  comando _'docker-compose -f docker-compose-development.yml up'_ e no final apresenta essa mensagem:

![1](https://user-images.githubusercontent.com/17239159/38340194-7b94b552-3848-11e8-99db-2a8794433351.png)

Devo usar outra abordagem?

**Comment by lucianojfj** [comment]
@KaiqueMunhoz Vou testar no meu Windows 10 e te digo algo depois.

**Comment by lucianojfj** [comment]
@KaiqueMunhoz Você instalou qual edição do Docker? "Docker Toolbox" ou  "Docker Community Edition for Windows"?

**Comment by KaiqueMunhoz** [comment]
Docker Toolbox version 18.01.0-ce

**Comment by lucianojfj** [comment]
@KaiqueMunhoz #102 e #104 resolveram. Tenta novamente por favor.

**Comment by KaiqueMunhoz** [comment]
Semana corrida...
O teste me retornou isso:
![image](https://user-images.githubusercontent.com/17239159/38763829-63553f3c-3f7a-11e8-99f7-55f31945f631.png)

E o novo arquivo do docker me retornou isso:
![image](https://user-images.githubusercontent.com/17239159/38763874-242f8636-3f7b-11e8-86ec-832827be8b44.png)

**Comment by lucianojfj** [comment]
@KaiqueMunhoz Funcionou. Perceba a ultima linha da segunda foto: **Listening on 0.0.0.0:3000, CTRL+C to stop**. Daí no teu browser, tenta acessar: `http://192.168.99.100:3000`

**Comment by alexanmtz** [comment]
Valeu @KaiqueMunhoz , qualquer dúvida é só falar!

**Comment by alexanmtz** [comment]
Algum progresso esta issue @KaiqueMunhoz ?

**Comment by eduardopastre** [comment]
Olá @alexanmtz, posso participar dessa Issue também mesmo já atribuída?

**Comment by alexanmtz** [comment]
Olá @eduardopastre , pode sim, na verdade está parada há um tempo e sem nenhum retorno, lhe enviei um convite e assim posso lhe atribuir e você pode começar e se tiver qualquer dúvida, só falar!

**Comment by eduardopastre** [comment]
@alexanmtz estou com o projeto rodando legal. Como não conheço bem o projeto, como acesso as páginas que precisam ser melhoradas?
- Página de lugares para explorar.
- Cadastro do guia.
E quais seriam as melhorias necessárias?

**Comment by alexanmtz** [comment]
@eduardopastre ótimas perguntas. Esta tarefa está parada há um tempo, então revisando aqui não se preocupe agora com a página de lugares para explorar, que ela está desabilitada no momento.

O cadastro do guia é esta página: [https://truppie.com/welcome/organizer](https://truppie.com/welcome/organizer)

A melhoria nela se você ver numa resolução menor, seria fazer ajustes no CSS para que ele fique adaptado ao mobile. Em experiências do dia a dia, são problemas que podem acontecer com alguma página que ainda não foi adaptada.

E a parte do bug que deixa no safari a logo em svg preta.

Qualquer dúvida e se quiser discutir a solução, é só falar!

**Comment by eduardopastre** [comment]
@alexanmtz estou enviando essas imagens pra você ver se fica bom assim no mobile, o formulário embaixo do facebook. Como na Web fica à direita, o natural é que ao se adaptar ao mobila ele desça, o que acha? Definindo isso só falta ajustar alguns detalhes.
A logo no Safari tive que mecher no svg para corrigir.

![screen shot 2018-05-27 at 01 14 36](https://user-images.githubusercontent.com/4492483/40582460-18522842-614e-11e8-8320-39edf74989a8.png)

![screen shot 2018-05-27 at 01 08 36](https://user-images.githubusercontent.com/4492483/40582497-c7946cd4-614e-11e8-93e8-905e3f2c7579.png)

![screen shot 2018-05-27 at 01 15 31](https://user-images.githubusercontent.com/4492483/40582504-ece985a0-614e-11e8-9ad6-28a421f75d5c.png)

**Comment by alexanmtz** [comment]
Perfeito @KaiqueMunhoz , é isso mesmo! 🎉

**Comment by alexanmtz** [comment]
Muito obrigado @eduardopastre, melhorou consideravelmente a experiência mobile, e já foi integrado no projeto e testado e já está no ar 🚀
