### ISSUE TITLE
Idioma oficial do projeto

### ISSUE THREAD

**Issue by lucianojfj** [worknenjoy/truppie#68]
Olá, sou novo aqui :)

Gostaria de entender do motivo pelo qual as _issues_ estarem sendo descritas em português.

Que tal usar algo mais global como o inglês?

P.S.: Fiquei na dúvida se este tipo de _issue_ que criei poderia estar aqui.

**Comment by alexanmtz** [comment]
É curioso você mencionar isto, pois estou criando as issues em português e os pull requests que estão chegando geralmente estão em inglês

Podemos seguir em inglês 👍
