### ISSUE TITLE
Identify clearly a version for gem 'bourbon' at Gemfile

### ISSUE THREAD

**Issue by lucianojfj** [worknenjoy/truppie#71]
The gem 'bourbon' is declared on version 4.3.4 at _Gemfile.lock_. However, in _Gemfile_ it's declared to get the latest version (5.0.0). Afterwards, when running the tests, several of them get failed. By now, declare the version 4.3.4 explicitly at _Gemfile_.

**Comment by lucianojfj** [comment]
@alexanmtz Please assign this issue for me.

**Comment by alexanmtz** [comment]
Sua versão foi integrada @lucianojfj , muito obrigado pela contribuição!
