### ISSUE TITLE
Message error when creating new account

### ISSUE THREAD

**Issue by lucianojfj** [worknenjoy/truppie#79]
Message error when creating new account is not displayed properly as follows:
![28547360_404055580041169_1453329773_o](https://user-images.githubusercontent.com/3276943/36789268-b4881376-1c6f-11e8-9945-f45a05b79abd.png)

@alexanmtz Are the message errors standardized? If so, is there other page displaying a message error following this standard?

**Comment by alexanmtz** [comment]
#54 #43 it suppose to fix these bugs and make the standard error message
