### ISSUE TITLE
Maps not loading anymore

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#81]
After #75 the maps is not loading on [tour pages](https://l.facebook.com/l.php?u=https%3A%2F%2Ftruppie.com%2Ftours%2F8-praia-de-castelhanos-aventura-4x4&h=ATMkCIxhWA8yh7ry0yUPrug3FADJkPjNhlK_RP8veut9Qa4_ZSJoXY2bKj5qUlBIPxqdcX2mJAU_G32airEhups2Og_ZItOTa6NQg2_21sr6Uzd9WgWSc3TW) and [explore page](https://truppie.com/welcome/user)

**Comment by biks152207** [comment]
codemill$30

**Comment by lucianojfj** [comment]
@alexanmtz Please assign me.

**Comment by alexanmtz** [comment]
Take a look at this @lucianojfj 
https://gorails.com/forum/getting-googlemaps-javascript-and-turbo-links-working-together

**Comment by lucianojfj** [comment]
@alexanmtz It didnt work. I have sent an alternative at #82.
