### ISSUE TITLE
The include and not included item is not spliting as tags

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#88]
### How to reproduze the user scenario

 - Create an user account
 - Create an organizer account
 - Create a tour (Truppie)
 - Use tags on "included" and "not included"

### Design or screenshot attached

![pageshot_of__truppie__ _2018-03-00-1350_52 1](https://user-images.githubusercontent.com/88840/37370088-6b92703e-270b-11e8-83d8-7607f954a962.png)

## Instructions of how to made the change proposal

Acceptance criteria

- [ ] When edit or create included and not included fields the tour view should display itens divided by tags

### Platform:

- Whats is used on the platform

### Requirements to run the project

- Ruby
- Postgres
- Be adminstrator
You need to create the `.env` file:

```
 ADMIN_EMAIL=youremail
 ADMIN_EMAIL_ALT=othermail
```

### How to work on this task

1. Make a comment here
2. You will be invited and be assign to the task
2. [Fork the project](https://help.github.com/articles/fork-a-repo/)
3. Clone the repo with `git clone` and run `rails s` to start the project

`rake test` (run tests and make sure is green)

`rails db:migrate` (Run the `migrations` for the database)

`rails s` (Rodar o projeto)

4. Make the necessary changes to this issue
5. [Send a pull request](https://help.github.com/articles/about-pull-requests/)
6. Verify if your changes didn't break the [automated tests](http://guides.rubyonrails.org/testing.html)
7. A new **application** will be created to be validated
8. You will receive feedback from team members
9. You will send changes until is approved
10. You get a approve 👍 
10. When the _Pull Request_ is merged, if is a paid task, the **payment is send**

If you have any doubt or need help just comment and you will be supported

### How to avoid issues when send the pull request

Para que seu Pull Request seja aceito sem maiores problemas e integrado diretamente para que possa ir para produção você deve sempre estar integrado com o master do projeto, **sempre usando rebase como padrão**.
You should be always up to date to the upstream master and use ***always rebase as default***

If you have doubts about it see [this post](http://www.arruda.blog.br/programacao/dicas-de-git-integrando-um-branch-no-master-rebase-ou-merge/)

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Itens de "O que inclui/não inclui" não ficam separados](https://trello.com/c/rzCmfSY0/9-itens-de-o-que-inclui-n%C3%A3o-inclui-n%C3%A3o-ficam-separados)

**Comment by lucianojfj** [comment]
@alexanmtz Please assign me.

**Comment by alexanmtz** [comment]
We will close this issue because it seems something general with the javascript loading

**Comment by alexanmtz** [comment]
https://github.com/worknenjoy/truppie/issues/88

**Comment by alexanmtz** [comment]
https://gitpay.me/#/task/48

**Comment by alexanmtz** [comment]
#142

**Comment by alexanmtz** [comment]
Great @pozzer , merged and deployed 🚀
