### ISSUE TITLE
Mailchimp integration

### ISSUE THREAD

**Issue by alexanmtz** [worknenjoy/truppie#99]
We would like to integrate the platform with [MailChimp](https://mailchimp.com/) lists.

It should be possible to add new users to the related list when a new user is registered or when they subscribe to the list on the home page form

So we have the following requirements to consider this task done:

- [ ] A rake task that add the current users to the user list (ID: 3bba2cbc78 )
- [ ] A rake task that add the current registered organizers to the guides list (ID: 8faafcc18b )
- [ ] A new registered `Organizer` should be added to the list (ID: 8faafcc18b )
- [ ] A new registered `User` should be added to the list (ID: 3bba2cbc78 )
- [ ] A user that send a message in contact form should be added to the list (ID: 3bba2cbc78 )
- [ ] The MailChimp keys should be in a env var and should not be exposed

More details in how to contribute, [read the contribution guidelines](https://github.com/worknenjoy/truppie/blob/master/CONTRIBUTING.md)

## PT-BR ##: 
Precisamos integrar a plataforma com listas do [MailChimp](https://mailchimp.com/)

Queremos que seja possível adicionar novos usuários para a lista relacionada quando um novo usuário é registrado ou quando ele é inscrito no formulário de inscrição na página inicial.

Temos os seguintes requisitos para considerar todas integrações:

- [ ] Uma task do rake para adicionar os usuários atuais na lista (ID: 3bba2cbc78 )
- [ ] Uma task rake que adiciona guias (organizer) para a lista de guias (ID: 8faafcc18b )
- [ ] Quando um `Organizer` é registrado, deveria ir para a lista (ID: 8faafcc18b )
- [ ] Um novo `User` registrado deve ser adicionado à lista (ID: 3bba2cbc78 )
- [ ] Um usuário que entra em contato pelo formulário de contato deveria ser adicionado a lista (ID: 3bba2cbc78 )
- [ ] As chaves do MailChimp devem estar em uma variável de ambiente e não deverá ser exposta.

PS. As credenciais serão enviadas assim que iniciar a tarefa.

**Comment by alexanmtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Integração com o Mailchimp para enviar para usuários e guias](https://trello.com/c/MJxxeCn0/677-integra%C3%A7%C3%A3o-com-o-mailchimp-para-enviar-para-usu%C3%A1rios-e-guias)

**Comment by alexanmtz** [comment]
I've invited you to join the team @abhi8686 and when you accept, I will assign you to this task and you can start!

**Comment by alexanmtz** [comment]
I assigned you @abhi8686, so you can start and let me know if you need help

**Comment by abhi8686** [comment]
Sure thanks,   
There are scenarios which you might have forgot
1:  what happens when user is deleted (unsubscribe or delete the user from mailchimp).
2: once the user clicks unsubscribe from email , We  cannot to be add to the list again


above are thyings are just scenarios should we take care or pass on.

**Comment by alexanmtz** [comment]
Yeah, you're right @abhi8686 , nice catch. 

1. If the user is deleted, we should unsubscribe as well
2. If they unsubscribe from email, we don't have a easy way to know until we call the api. So the rake task that adds for a `User` and `Organizer` should sync and exclude the unsubscribes 

What you think?

**Comment by abhi8686** [comment]
we can pass on scenario 2 , its not that much needed !!
i think 1 is mandatory !

**Comment by alexanmtz** [comment]
Yeah, right @abhi8686! Actually we can skip both as we never deleted a user and we don't have a account delete function and a section to setup notifications, so for now let's cover the scenarios, but it's good to know and thanks for the considerations, we will keep in mind to address in another moment.

**Comment by alexanmtz** [comment]
How is going with this @abhi8686 ?

**Comment by alexanmtz** [comment]
I will leave this task open again, because it's been a while without any feedback about the progress of this...

**Comment by alexanmtz** [comment]
@lucasm0ura issue atualizada para o português para você entender melhor. Me avisa quando for começar que te envio a chave de API do mailchimp para que você possa testar, ou se preferir pode fazer com testes automatizados e simular com mocks

**Comment by lucasm0ura** [comment]
Certo @alexanmtz, assim que terminar umas pendências já coloco esta Issue para ser implementada. Assim que começar eu já te aviso.
See you !

**Comment by alexanmtz** [comment]
@lucasm0ura para esta tarefa foi dada uma recompensa de $15 para quem finalizá-la, basta cadastrar aqui para você receber quando fecharmos a issue:
https://www.bountysource.com/issues/56639153-mailchimp-integration

Se precisar de ajuda é só falar!

**Comment by alexanmtz** [comment]
@lucasm0ura , tem outra recompensa de $20 para finalização desta tarefa na nossa plataforma em beta:
https://gitpay.me/#/task/5

Cadastre-se para receber também por lá quando fecharmos esta issue 📆 💸

**Comment by lucasm0ura** [comment]
@alexanmtz  
Iniciando a instalação da GEM para o MailChimp.
Irei criar uma conta no MailChimp pra poder fazer os testes. Assim que concluir peço a Key + lista a ser inserido os emails.

**Comment by lucasm0ura** [comment]
A rake task that add the current users to the user list (ID: 3bba2cbc78 ) - DONE !

**Comment by lucasm0ura** [comment]
A rake task that add the current registered organizers to the guides list (ID: 8faafcc18b ) - DONE !

**Comment by lucasm0ura** [comment]
@alexanmtz  preciso novamente de permissão para poder dá commit na minha branch .

**Comment by alexanmtz** [comment]
@lucasm0ura ótima estratégia sobre as keys, se funcionar no seu caso, pode enviar o pull request que a gente testa num ambiente de testes com as chaves reais.

Sobre o commit, você precisa dar commit na branch no seu fork e fazer o pull request.

Se tiver dúvidas de como fazer isto, só falar. Para não perder nada basta dar um push pro seu origin para ir para o seu fork e não para o projeto principal

**Comment by lucasm0ura** [comment]
A new registered Organizer should be added to the list (ID: 8faafcc18b ) - DONE !
A new registered User should be added to the list (ID: 3bba2cbc78 ) - DONE !

**Comment by lucasm0ura** [comment]
As chaves do MailChimp devem estar em uma variável de ambiente e não deverá ser exposta. - DONE !

**Comment by lucasm0ura** [comment]
A user that send a message in contact form should be added to the list (ID: 3bba2cbc78 ) - DONE
  The MailChimp keys should be in a env var and should not be exposed - DONE !

**Comment by lucasm0ura** [comment]
@alexanmtz eu atualizei a master do projeto principal, copiei o projeto do truppie/master para lucasm0ura/master ( junto com minhas alterações ). Caso issso ocorra algum problema, pode entrar em contato comigo pra eu poder fazer o ajuste .

**Comment by lucasm0ura** [comment]
@alexanmtz vou tentar fazer os ajustes hoje, minha internet está ruim faz 2 dias. Obrigado pela paciência !

**Comment by alexanmtz** [comment]
#128 #126

**Comment by alexanmtz** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀
